---
title: "ggplot"
author: "Qimin Zhang"
date: "9/26/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(ggridges)
```

```{r, collapse = TRUE, message = FALSE}
weather_df = 
  rnoaa::meteo_pull_monitors(c("USW00094728", "USC00519397", "USS0023B17S"),
                      var = c("PRCP", "TMIN", "TMAX"), 
                      date_min = "2017-01-01",
                      date_max = "2017-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY", 
                      USC00519397 = "Waikiki_HA",
                      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
weather_df
```
Create a ggplot.
```{r, message = FALSE, warning = FALSE}
ggplot(weather_df, aes(x = tmin, y = tmax)) +
  geom_point()
```
Alternative way to make this plot.
```{r, message = FALSE, warning = FALSE}
weather_df %>%
  ggplot(aes(x = tmin, y = tmax)) +
    geom_point()
```
Saving initial plots, mostly I don't do this.
```{r, message = FALSE, warning = FALSE}
scatterplot = 
  weather_df %>%
  ggplot(aes(x = tmin, y = tmax)) +
    geom_point()

scatterplot
```
Adding color...
```{r, message = FALSE, warning = FALSE}
weather_df %>%
  ggplot(aes(x = tmin, y = tmax)) +
    geom_point(aes(color = name), alpha = .4)
```
Why do 'aes' positions matter? If I use 'color =' in a global scale, then all plots in this graph would be influenced.
```{r, message = FALSE, warning = FALSE}
weather_df %>%
  ggplot(aes(x = tmin, y = tmax, color = name)) +
    geom_point(alpha = .4) +
    geom_smooth(se = FALSE)
```
Facet!
```{r, message = FALSE, warning = FALSE}
weather_df %>%
  ggplot(aes(x = tmin, y = tmax, color = name)) +
    geom_point(alpha = .4) +
    geom_smooth(se = FALSE) +
    facet_grid(. ~ name)
```
Let's make some interesting plots.
```{r, message = FALSE, warning = FALSE}
ggplot(weather_df, aes(x = date, y = tmax, color = name)) + 
  geom_point(aes(size = prcp), alpha = .5) +
  geom_smooth(se = FALSE)

ggplot(weather_df, aes(x = date, y = tmax, color = name)) + 
  geom_point(aes(size = prcp), alpha = .5) +
  geom_smooth(se = FALSE) + 
  facet_grid(. ~ name)
```
Only showing the smooth curve?
```{r, message = FALSE, warning = FALSE}
ggplot(weather_df, aes(x = date, y = tmax, color = name)) + 
  geom_smooth(se = FALSE) 
```
```{r, message = FALSE, warning = FALSE}
ggplot(weather_df, aes(x = date, y = tmax)) + 
  geom_hex()
```
More kinds of plots.
```{r, message = FALSE, warning = FALSE}
#Histogram
ggplot(weather_df, aes(x = tmax, fill = name)) + 
  geom_histogram()

ggplot(weather_df, aes(x = tmax, fill = name)) + 
  geom_histogram(position = "dodge", binwidth = 2)
```
```{r, message = FALSE, warning = FALSE}
#Density plot
ggplot(weather_df, aes(x = tmax, fill = name)) + 
  geom_density(alpha = .4, adjust = .5, color = "blue")
```
```{r, message = FALSE, warning = FALSE}
#Boxplot
ggplot(weather_df, aes(x = name, y = tmax)) + 
  geom_boxplot()
```
```{r, message = FALSE, warning = FALSE}
#Violin plot
ggplot(weather_df, aes(x = name, y = tmax)) + 
  geom_violin(aes(fill = name), color = "blue", alpha = .5) + 
  stat_summary(fun.y = median, geom = "point", color = "blue", size = 4)
```
```{r, message = FALSE, warning = FALSE}
#Ridge plot
ridge_temp =
  ggplot(weather_df, aes(x = tmax, y = name)) + 
    geom_density_ridges(scale = .85)
ggsave("gglpot_tmp_riage.pdf", ridge_temp)
```



